# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'dotenv-rails'
gem 'lago-ruby-client'
gem 'puma'
gem 'redis'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'stripe'
